### ISSUE TITLE
[BUG] ALLOW_* options only work if POST is granted

### ISSUE THREAD

**Issue by Cheezzhead** [linuxserver/docker-socket-proxy#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`ALLOW_START`, `ALLOW_STOP`, `ALLOW_RESTARTS` are all `POST` methods. 

Currently, the behavior is:
- If `POST=0`, the start/stop/restart operations are denied irregardless of the above environment variables.
- If `POST=1`, the operations are allowed even if the above environment variables are set to `0`.

So as it stands, these permissions have no practical effect. 

I would assume the problem is easily fixed by adjusting the respective `limit_except` directives in the template files, e.g.:
```
# Old
location ~* ^(/v[\d\.]+)?/containers/[a-zA-Z0-9_.-]+/((stop)|(restart)|(kill)) {limit_except GET HEAD {deny all;}if ($path_restarts = 0){return 403;}proxy_pass http://unix:$dockersocket;}

# New
location ~* ^(/v[\d\.]+)?/containers/[a-zA-Z0-9_.-]+/((stop)|(restart)|(kill)) {limit_except GET HEAD POST {deny all;}if ($path_restarts = 0){return 403;}proxy_pass http://unix:$dockersocket;}
```
(Side note: I would also leave out HEAD because it is implied by GET)

### Expected Behavior

The `ALLOW_` permissions should supercede the `POST` permissions, or they should be deprecated.

### Steps To Reproduce

Attempting to start/stop/restart a container in (for example) Portainer will fail, using the configuration provided below.

### Environment

```markdown
- OS:Ubuntu 20.04
- How docker service was installed: Compose
```

### Docker creation

```yaml
services:
  docker-socket:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: docker-socket
    read_only: true
    tmpfs:
      - /run
    env_file: docker-socket.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

`docker-socket.env`:
```bash
DISABLE_IPV6=0

# Granted
#########
EVENTS=1
PING=1
VERSION=1
ALLOW_START=1
ALLOW_STOP=1
ALLOW_RESTARTS=1

# Portainer
CONTAINERS=1
IMAGES=1
INFO=1
NETWORKS=1
SERVICES=1
TASKS=1
VOLUMES=1

# Revoked
#########
# Security critical
AUTH=0
SECRETS=0
POST=0

# Not necessary
BUILD=0
COMMIT=0
CONFIGS=0
DISTRIBUTION=0
EXEC=0
NODES=0
PLUGINS=0
SESSION=0
SWARM=0
SYSTEM=0
```

### Container logs

```bash
// ...
2024/08/20 12:58:40 [error] 47#47: *3472 access forbidden by rule, client: X.X.X.X, server: _, request: "POST /containers/<CONTAINER_UUID>/pause HTTP/1.1", host: "docker-socket:2375", referrer: "https://portainer.domain.tld/"
// ...
```
